//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Options_Handler", Namespace="http://schemas.datacontract.org/2004/07/DynamicDataWebSite")]
    public partial class Options_Handler : object
    {
        
        private string AddressField;
        
        private string CatField;
        
        private System.Nullable<int> City_IDField;
        
        private System.Nullable<int> Contract_TypeField;
        
        private System.Nullable<int> Country_IDField;
        
        private System.DateTime DateField;
        
        private System.DateTime Date_AddedField;
        
        private string EmailField;
        
        private string ExpectedEntryField;
        
        private System.DateTime Expire_DateField;
        
        private string FirstNameField;
        
        private int FloorField;
        
        private bool GarageField;
        
        private bool GardenField;
        
        private System.Nullable<bool> Has_GarageField;
        
        private System.Nullable<bool> Has_GardenField;
        
        private long IdField;
        
        private string LangField;
        
        private string LastNameField;
        
        private string LocationField;
        
        private int Num_BathroomsField;
        
        private int Num_BedroomsField;
        
        private System.Nullable<int> Num_FloorsField;
        
        private string OldpasswordField;
        
        private string Other_DetailsField;
        
        private string PasswordField;
        
        private string PhoneField;
        
        private DataService.FileStream PhotostreamField;
        
        private int PropertyIDField;
        
        private int Property_Category_IDField;
        
        private string Property_Id_extField;
        
        private string Property_PhotoField;
        
        private int Property_SizeField;
        
        private int Property_Type_IDField;
        
        private System.Nullable<int> Rent_PriceField;
        
        private System.Nullable<int> Sale_PriceField;
        
        private string TypeField;
        
        private string Url_extField;
        
        private string User_IDField;
        
        private string Zip_CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cat
        {
            get
            {
                return this.CatField;
            }
            set
            {
                this.CatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> City_ID
        {
            get
            {
                return this.City_IDField;
            }
            set
            {
                this.City_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Contract_Type
        {
            get
            {
                return this.Contract_TypeField;
            }
            set
            {
                this.Contract_TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Country_ID
        {
            get
            {
                return this.Country_IDField;
            }
            set
            {
                this.Country_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Added
        {
            get
            {
                return this.Date_AddedField;
            }
            set
            {
                this.Date_AddedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpectedEntry
        {
            get
            {
                return this.ExpectedEntryField;
            }
            set
            {
                this.ExpectedEntryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Expire_Date
        {
            get
            {
                return this.Expire_DateField;
            }
            set
            {
                this.Expire_DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Floor
        {
            get
            {
                return this.FloorField;
            }
            set
            {
                this.FloorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Garage
        {
            get
            {
                return this.GarageField;
            }
            set
            {
                this.GarageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Garden
        {
            get
            {
                return this.GardenField;
            }
            set
            {
                this.GardenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Has_Garage
        {
            get
            {
                return this.Has_GarageField;
            }
            set
            {
                this.Has_GarageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Has_Garden
        {
            get
            {
                return this.Has_GardenField;
            }
            set
            {
                this.Has_GardenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Num_Bathrooms
        {
            get
            {
                return this.Num_BathroomsField;
            }
            set
            {
                this.Num_BathroomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Num_Bedrooms
        {
            get
            {
                return this.Num_BedroomsField;
            }
            set
            {
                this.Num_BedroomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Num_Floors
        {
            get
            {
                return this.Num_FloorsField;
            }
            set
            {
                this.Num_FloorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Oldpassword
        {
            get
            {
                return this.OldpasswordField;
            }
            set
            {
                this.OldpasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Other_Details
        {
            get
            {
                return this.Other_DetailsField;
            }
            set
            {
                this.Other_DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataService.FileStream Photostream
        {
            get
            {
                return this.PhotostreamField;
            }
            set
            {
                this.PhotostreamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyID
        {
            get
            {
                return this.PropertyIDField;
            }
            set
            {
                this.PropertyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Property_Category_ID
        {
            get
            {
                return this.Property_Category_IDField;
            }
            set
            {
                this.Property_Category_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Property_Id_ext
        {
            get
            {
                return this.Property_Id_extField;
            }
            set
            {
                this.Property_Id_extField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Property_Photo
        {
            get
            {
                return this.Property_PhotoField;
            }
            set
            {
                this.Property_PhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Property_Size
        {
            get
            {
                return this.Property_SizeField;
            }
            set
            {
                this.Property_SizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Property_Type_ID
        {
            get
            {
                return this.Property_Type_IDField;
            }
            set
            {
                this.Property_Type_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Rent_Price
        {
            get
            {
                return this.Rent_PriceField;
            }
            set
            {
                this.Rent_PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sale_Price
        {
            get
            {
                return this.Sale_PriceField;
            }
            set
            {
                this.Sale_PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url_ext
        {
            get
            {
                return this.Url_extField;
            }
            set
            {
                this.Url_extField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_ID
        {
            get
            {
                return this.User_IDField;
            }
            set
            {
                this.User_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip_Code
        {
            get
            {
                return this.Zip_CodeField;
            }
            set
            {
                this.Zip_CodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileStream", Namespace="http://schemas.datacontract.org/2004/07/System.IO")]
    public partial class FileStream : byte[]
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City_Handler", Namespace="http://schemas.datacontract.org/2004/07/DynamicDataWebSite")]
    public partial class City_Handler : object
    {
        
        private int City_IDField;
        
        private string City_Latin_NameField;
        
        private string City_NameField;
        
        private string City_Native_NameField;
        
        private int Country_IDField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int City_ID
        {
            get
            {
                return this.City_IDField;
            }
            set
            {
                this.City_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City_Latin_Name
        {
            get
            {
                return this.City_Latin_NameField;
            }
            set
            {
                this.City_Latin_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City_Name
        {
            get
            {
                return this.City_NameField;
            }
            set
            {
                this.City_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City_Native_Name
        {
            get
            {
                return this.City_Native_NameField;
            }
            set
            {
                this.City_Native_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Country_ID
        {
            get
            {
                return this.Country_IDField;
            }
            set
            {
                this.Country_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country_Handler", Namespace="http://schemas.datacontract.org/2004/07/DynamicDataWebSite")]
    public partial class Country_Handler : object
    {
        
        private string Country_CodeField;
        
        private int Country_IDField;
        
        private string Country_NameField;
        
        private string Country_Native_NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country_Code
        {
            get
            {
                return this.Country_CodeField;
            }
            set
            {
                this.Country_CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Country_ID
        {
            get
            {
                return this.Country_IDField;
            }
            set
            {
                this.Country_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country_Name
        {
            get
            {
                return this.Country_NameField;
            }
            set
            {
                this.Country_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country_Native_Name
        {
            get
            {
                return this.Country_Native_NameField;
            }
            set
            {
                this.Country_Native_NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.ITelegram_Handler")]
    public interface ITelegram_Handler
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegram_Handler/_Add_User", ReplyAction="http://tempuri.org/ITelegram_Handler/_Add_UserResponse")]
        System.Threading.Tasks.Task<string> _Add_UserAsync(DataService.Options_Handler handler, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegram_Handler/Test", ReplyAction="http://tempuri.org/ITelegram_Handler/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegram_Handler/_User_Exist", ReplyAction="http://tempuri.org/ITelegram_Handler/_User_ExistResponse")]
        System.Threading.Tasks.Task<bool> _User_ExistAsync(DataService.Options_Handler handler, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegram_Handler/_Update_User", ReplyAction="http://tempuri.org/ITelegram_Handler/_Update_UserResponse")]
        System.Threading.Tasks.Task<string> _Update_UserAsync(DataService.Options_Handler handler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegram_Handler/_Add_Property", ReplyAction="http://tempuri.org/ITelegram_Handler/_Add_PropertyResponse")]
        System.Threading.Tasks.Task<string> _Add_PropertyAsync(DataService.Options_Handler property, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegram_Handler/_Get_Property_List", ReplyAction="http://tempuri.org/ITelegram_Handler/_Get_Property_ListResponse")]
        System.Threading.Tasks.Task<DataService.Options_Handler[]> _Get_Property_ListAsync(DataService.Options_Handler handler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegram_Handler/_Update_Property", ReplyAction="http://tempuri.org/ITelegram_Handler/_Update_PropertyResponse")]
        System.Threading.Tasks.Task<string> _Update_PropertyAsync(DataService.Options_Handler property, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegram_Handler/_Get_City_List", ReplyAction="http://tempuri.org/ITelegram_Handler/_Get_City_ListResponse")]
        System.Threading.Tasks.Task<DataService.City_Handler[]> _Get_City_ListAsync(int cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegram_Handler/_Get_Country_List", ReplyAction="http://tempuri.org/ITelegram_Handler/_Get_Country_ListResponse")]
        System.Threading.Tasks.Task<DataService.Country_Handler[]> _Get_Country_ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegram_Handler/_Get_Property_Value", ReplyAction="http://tempuri.org/ITelegram_Handler/_Get_Property_ValueResponse")]
        System.Threading.Tasks.Task<DataService.Options_Handler> _Get_Property_ValueAsync(DataService.Options_Handler handler, string address, string date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface ITelegram_HandlerChannel : DataService.ITelegram_Handler, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class Telegram_HandlerClient : System.ServiceModel.ClientBase<DataService.ITelegram_Handler>, DataService.ITelegram_Handler
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Telegram_HandlerClient() : 
                base(Telegram_HandlerClient.GetDefaultBinding(), Telegram_HandlerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITelegram_Handler.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Telegram_HandlerClient(EndpointConfiguration endpointConfiguration) : 
                base(Telegram_HandlerClient.GetBindingForEndpoint(endpointConfiguration), Telegram_HandlerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Telegram_HandlerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Telegram_HandlerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Telegram_HandlerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Telegram_HandlerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Telegram_HandlerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> _Add_UserAsync(DataService.Options_Handler handler, string token)
        {
            return base.Channel._Add_UserAsync(handler, token);
        }
        
        public System.Threading.Tasks.Task<string> TestAsync()
        {
            return base.Channel.TestAsync();
        }
        
        public System.Threading.Tasks.Task<bool> _User_ExistAsync(DataService.Options_Handler handler, string token)
        {
            return base.Channel._User_ExistAsync(handler, token);
        }
        
        public System.Threading.Tasks.Task<string> _Update_UserAsync(DataService.Options_Handler handler)
        {
            return base.Channel._Update_UserAsync(handler);
        }
        
        public System.Threading.Tasks.Task<string> _Add_PropertyAsync(DataService.Options_Handler property, string token)
        {
            return base.Channel._Add_PropertyAsync(property, token);
        }
        
        public System.Threading.Tasks.Task<DataService.Options_Handler[]> _Get_Property_ListAsync(DataService.Options_Handler handler)
        {
            return base.Channel._Get_Property_ListAsync(handler);
        }
        
        public System.Threading.Tasks.Task<string> _Update_PropertyAsync(DataService.Options_Handler property, string token)
        {
            return base.Channel._Update_PropertyAsync(property, token);
        }
        
        public System.Threading.Tasks.Task<DataService.City_Handler[]> _Get_City_ListAsync(int cid)
        {
            return base.Channel._Get_City_ListAsync(cid);
        }
        
        public System.Threading.Tasks.Task<DataService.Country_Handler[]> _Get_Country_ListAsync()
        {
            return base.Channel._Get_Country_ListAsync();
        }
        
        public System.Threading.Tasks.Task<DataService.Options_Handler> _Get_Property_ValueAsync(DataService.Options_Handler handler, string address, string date)
        {
            return base.Channel._Get_Property_ValueAsync(handler, address, date);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITelegram_Handler))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITelegram_Handler))
            {
                return new System.ServiceModel.EndpointAddress("http://weappweb-001-site1.btempurl.com/Services/Telegram_Handler.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Telegram_HandlerClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITelegram_Handler);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Telegram_HandlerClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITelegram_Handler);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITelegram_Handler,
        }
    }
}
